moved logging functions to stdlib

diff --git a/pscl b/pscl
--- a/pscl
+++ b/pscl
@@ -1,13 +1,7 @@
 #!/bin/sh
 
-# shellcheck source=./stdlib.sh
-# shellcheck source=./backend.sh
-
-readonly red="\x1b[31m"
-readonly blue="\x1b[34m"
-readonly yellow="\x1b[33m"
-readonly green="\x1b[32m"
-readonly def="\x1b[39m"
+# shellcheck source=stdlib.sh
+# shellcheck source=backend.sh
 
 readonly PKGDIR="${PKGDIR:-"$(realpath "$(dirname "$0")")"}"
 readonly METADATA_DIR="${PKGDIR}/metadata"
@@ -17,6 +11,8 @@ readonly CACHE_DIR="${CACHE_DIR:-${PKGDIR}/source_cache}"
 readonly PACKAGE_CACHE="${PACKAGE_CACHE:-${PKGDIR}/package_cache}"
 readonly REPOSITORY_LIST="${REPOSITORY_LIST:-${PKGDIR}/repositories/main}"
 readonly EXTENSION_DIR="${PKGDIR:?}/extensions"
+
+readonly green="\x1b[32m"
 
 parse_arguments() {
     _flag="$1"
@@ -242,32 +238,6 @@ print_usage() {
     exit 0
 }
 
-log_error() {
-    if [ -n "${BASH_VERSION+x}" ]; then
-        _msg_prefix=" In ${FUNCNAME[1]}: (line ${BASH_LINENO[0]})"
-    elif [ -n "${ZSH_VERSION+x}" ]; then
-        _msg_prefix=" In ${funcstack[2]}:"
-    fi
-
-    printf "%b[ERROR]%b%s: %s\n" "$red" "$def" "${_msg_prefix:-}" "$1" >&2
-    exit 1
-}
-
-log_warn() {
-    printf "%b[WARNING]%b: %s\n" "$yellow" "$def" "$1" >&2
-}
-
-log_debug() {
-    if [ -n "${BASH_VERSION+x}" ]; then
-        _msg_prefix=" In ${FUNCNAME[1]}: (line ${BASH_LINENO[0]})"
-    elif [ -n "${ZSH_VERSION+x}" ]; then
-        _msg_prefix=" In ${funcstack[2]}:"
-    fi
-
-    [ "${VERBOSE:-0}" = 1 ] && \
-        printf "%b[DEBUG]%b%s: %s\n" "$blue" "$def" "${_msg_prefix:-}" "$1" >&2
-}
-
 install_package() (
     _pkg_name="$1"
 
@@ -472,10 +442,9 @@ main_query() (
 )
 
 load_extensions() {
-    log_debug "Extension dir is: $EXTENSION_DIR"
 
-    . ./stdlib.sh || log_error "Failed to load stdlib"
-    . ./backend.sh || log_error "Failed to load backend"
+    . stdlib.sh || exit 1
+    . backend.sh || log_error "Failed to load backend"
 
     [ -d "$EXTENSION_DIR" ] || \
         log_warn "Extenstion directory does not exist: $EXTENSION_DIR"
@@ -486,7 +455,6 @@ load_extensions() {
             continue 
         fi
 
-        log_debug "Loading extension: $ext"
         [ -f "$ext" ] || continue
         . "$ext" || log_error "Failed to load extension: $ext"
     done
